cache:
  untracked: true
  key: $CI_BUILD_REF_NAME
  paths:
  - node_modules/

stages:
- install
- lint
- test

install-stage:
  stage: install
  script:
  - npm install

lint-stage:
  stage: lint
  script:
  - npm run lint

test-stage:
  stage: test
  script:
  - npm run test
