version: "3.6"
services:
  web:
    build: .

    expose:
      - "${HTTP_PORT}"

    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    links:
      - mongo

    depends_on:
      - mongo


  mongo:
    image: mongo

    command: "mongod --port ${MONGO_DB_PORT}"

    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"


